---
# Install jq

- name: Set jessie source list in apt
  apt_repository: 
    repo: "deb ftp://ftp.gr.debian.org/debian/ jessie main"
    state: present
    mode: 0644
#  when: ansible_lsb.codename == "jessie"

- name: Set jessie source list in apt
  apt_repository: 
    repo: "deb-src ftp://ftp.gr.debian.org/debian/ jessie main"
    state: present
    mode: 0644
#  when: ansible_lsb.codename == "jessie"

- name: Install jq and update apt's cache
  apt:
    name: jq
    state: latest
    update_cache: yes
